// This file is auto generated by build/build-entry.js
import Button from './button';

const version = '1.0.0';
const components = [
  Button
];

const install = Vue => {
  components.forEach(Component => {
    Vue.use(Component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  install,
  version,
  Button
};

export default {
  install,
  version
};
